compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 1
  fp16:
    enabled: false
  bf16:
    enabled: true
  optimizer:
    type: AdamW
    params:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 1e-8
      weight_decay: 0.01
  scheduler:
    type: WarmupLR
    params:
      warmup_min_lr: 0
      warmup_max_lr: 0.001
      warmup_num_steps: 1000
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false